#Basic Config
spring.application.name=API-Gateway
server.port=8010

# Default filter
spring.cloud.gateway.default-filters[0]=AddRequestHeader=X-Gateway,law-system

# ===== LAWYER SERVICE =====
spring.cloud.gateway.routes[0].id=Lawyer-Service
spring.cloud.gateway.routes[0].uri=http://localhost:8011
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/lawyers/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

# ===== LAWCASE SERVICE =====
spring.cloud.gateway.routes[1].id=LawCase-Service
spring.cloud.gateway.routes[1].uri=http://localhost:8012
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/cases/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2

# ===== LAWCLIENT SERVICE =====
spring.cloud.gateway.routes[2].id=LawClient-Service
spring.cloud.gateway.routes[2].uri=http://localhost:8013
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/clients/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=2