#Basic Config
spring.application.name=LawCase-Service
server.port=8012
#Actuator
management.endpoints.web.exposure.include= health,info,metrics,prometheus
management.endpoint.health.show-details=always

# Adres serwera MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/lawoffice2026